# Generated by Django 4.0.3 on 2022-05-09 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_amendment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amendment',
            name='decision_date',
        ),
    ]
