# Generated by Django 4.0.3 on 2022-05-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_harddrive_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harddrive',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
